version: '3'
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./app:/go/src/app
    depends_on:
      - 'db'
  db:
    container_name: beego-tutorial-mysql
    image: mysql:5.7
    volumes:
      - ./db/conf:/etc/mysql/conf.d
      - ./db/logs:/var/log/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: beego
      MYSQL_USER: beego
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
